#include <precomp.h>
#include "ClipXClipboardMonitor.h"

// CLIPX PLUGIN SDK - DO NOT MODIFY

#define CBCLASS ClipXClipboardMonitorI
START_DISPATCH;
  CB(SVC_CLIPX_CLIPBOARDMONITOR_ONNEWTEXTCLIPBOARD, onNewTextClipboard);
  CB(SVC_CLIPX_CLIPBOARDMONITOR_ONNEWBITMAPCLIPBOARD, onNewBitmapClipboard);
  CB(SVC_CLIPX_CLIPBOARDMONITOR_ONNEWDIBITMAPCLIPBOARD, onNewDIBitmapClipboard);
  CB(SVC_CLIPX_CLIPBOARDMONITOR_ONNEWFILELISTCLIPBOARD, onNewFileListClipboard);
END_DISPATCH;
#undef CBCLASS
