#include <precomp.h>
#include "ClipXPopupModifier.h"

// CLIPX PLUGIN SDK - DO NOT MODIFY

#define CBCLASS ClipXPopupModifierI
START_DISPATCH;
  VCB(SVC_CLIPX_POPUPMODIFIER_CUSTOMIZESYSTRAY, customizeSystrayMenu);
  VCB(SVC_CLIPX_POPUPMODIFIER_CUSTOMIZEHISTORY, customizeHistoryMenu);
  VCB(SVC_CLIPX_POPUPMODIFIER_ONCUSTOMSIZE, onCustomSize);
  VCB(SVC_CLIPX_POPUPMODIFIER_ONCUSTOMDRAW, onCustomDraw);
  CB(SVC_CLIPX_POPUPMODIFIER_ONCUSTOMACCELERATOR, onCustomAccelerator);
  VCB(SVC_CLIPX_POPUPMODIFIER_ONCOMMAND, onCommand);
  VCB(SVC_CLIPX_POPUPMODIFIER_ONDELETEMENU, onDeleteMenu);
END_DISPATCH;
#undef CBCLASS
